#!/usr/bin/env bash
# This script configures the nginx server so that /redirect_me is redirecting to
# another page.
sudo apt update
sudo apt install nginx -y
sudo sed -i "/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
sudo service nginx restart
